POST http://localhost:3001/api/blogs/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhc2kiLCJpZCI6IjVlNGM1N2VlMDNmZTQ1Mjg5NmM0NzY3NSIsImlhdCI6MTU4MjA2MTU2MH0.m01tvfmDWrbn1UyCOJLtUJFXnAQtab6IpAk7rCG7e2A

{
  "title":"Mullan Alta",
  "author": "Ilari Aalto",
  "url": "https://mullanalta.blogspot.com/",
  "likes": 9000
}